/*
 * Independent end-to-end validation that every SNPmer generated by myloasm
 * becomes a dinara anchor at the correct position.
 *
 * Three layers of checking:
 *
 *  A. SNP-column correctness (per occurrence, independent of dinara):
 *     for each snpmer marker on a read, the canonical middle base of the key
 *     must equal one of the two alleles of the k-mer, and the FORWARD read base
 *     at snpCol = pos + mid must decode to a base -- i.e. snpCol is a real SNP
 *     column inside the read.
 *
 *  B. Producer-model prediction (replicates Shasta2SnpmerAnchors.cpp EXACTLY):
 *     bucket occurrences on dinara-KEPT reads by canonical key; DROP any read
 *     that carries a key more than once (repeat: ambiguous column); drop reads
 *     shared by both alleles of a split (paralog); require both alleles >=
 *     minMembers (biallelic). Each occurrence is placed in its canonical k-mer
 *     orientation o (0 if forward k-mer == key, else 1). The canonical anchor
 *     sits on strand o at column canonCol = (o==0? snpCol : L - snpCol); the RC
 *     anchor sits on strand o^1 at L - canonCol. (appendHetAnchorPair stores
 *     rawPosition + hetKHalf and mirrors to the opposite strand at L - column.)
 *     Per-occurrence orientation keeps genomic-forward and genomic-reverse
 *     reads on the same strand for a given allele, so shasta2 sees a single
 *     intra-read order and does not build A<->B 2-cycles.
 *
 *  C. Cross-check vs dinara's actual store (DINARA_SNPMER_DUMP output):
 *     the predicted (key, readName, strand, storedPos) set must EQUAL the dumped
 *     set -- no missing predictions, no extra dump rows, and every position must
 *     match exactly.
 *
 * Usage:
 *   validate_snpmer_anchors <reads.fastq> <ReadSummary.csv> <dump.tsv> [threads]
 */
#include "myloasm_ffi.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <zlib.h>

static inline uint8_t enc(char c){
    switch(c){case 'A':case 'a':return 0;case 'C':case 'c':return 1;
              case 'G':case 'g':return 2;case 'T':case 't':return 3;default:return 255;}
}

static void readFastq(const char* file,
                      std::unordered_map<std::string,std::string>& out){
    gzFile fp=gzopen(file,"r"); if(!fp){fprintf(stderr,"gzopen %s failed\n",file);exit(1);}
    char buf[1<<16]; int field=0; std::string name;
    auto gl=[&](std::string& d)->bool{d.clear();
        while(gzgets(fp,buf,sizeof(buf))){d+=buf;
            if(!d.empty()&&d.back()=='\n'){d.pop_back();return true;}}
        return !d.empty();};
    std::string l;
    while(gl(l)){
        if(field==0){size_t sp=l.find_first_of(" \t");
            name=l.substr(1,(sp==std::string::npos?l.size():sp)-1);}
        else if(field==1){out[name]=l;}
        field=(field+1)&3;
    }
    gzclose(fp);
}

/* dinara ReadSummary.csv -> set of kept read names (+ their length). */
static void readSummary(const char* file,
                        std::unordered_map<std::string,uint32_t>& keptLen){
    FILE* f=fopen(file,"r"); if(!f){fprintf(stderr,"open %s failed\n",file);exit(1);}
    char* line=nullptr; size_t cap=0; ssize_t n; bool header=true;
    while((n=getline(&line,&cap,f))>0){
        if(header){header=false;continue;}
        /* Id,Name,Length,... */
        char* p=line; char* c1=strchr(p,','); if(!c1)continue;
        char* c2=strchr(c1+1,','); if(!c2)continue;
        char* c3=strchr(c2+1,','); if(!c3)continue;
        std::string name(c1+1,c2-(c1+1));
        uint32_t len=(uint32_t)strtoul(c2+1,nullptr,10);
        keptLen[name]=len;
    }
    free(line); fclose(f);
}

int main(int argc,char** argv){
    if(argc<4){
        fprintf(stderr,"usage: %s <reads.fastq> <ReadSummary.csv> <dump.tsv> [threads]\n",argv[0]);
        return 2;
    }
    const char* fastq=argv[1]; const char* summary=argv[2]; const char* dump=argv[3];
    int threads=argc>=5?atoi(argv[4]):8;

    /* ---- index reads with myloasm (same call dinara makes) ---- */
    const char* files[1]={fastq};
    MyloReadIndex idx; std::memset(&idx,0,sizeof(idx));
    if(myloasm_index_reads(files,1,0,0,threads,&idx)!=0){
        fprintf(stderr,"myloasm_index_reads failed\n"); return 2;
    }
    const int k=idx.k, mid=(k-1)/2;
    fprintf(stderr,"[val] myloasm reads=%zu k=%d\n",idx.n_reads,k);

    std::unordered_map<std::string,std::string> seqByName; readFastq(fastq,seqByName);
    std::unordered_map<std::string,uint32_t> keptLen; readSummary(summary,keptLen);
    fprintf(stderr,"[val] fastq parsed=%zu, dinara-kept reads=%zu\n",
            seqByName.size(),keptLen.size());

    const uint64_t fullMask=(k>=32)?~0ULL:((1ULL<<(2*k))-1ULL);
    const uint64_t splitMask=fullMask & ~(3ULL<<(2*mid));
    const uint64_t minMembers=2;

    /* ================= LAYER A: SNP-column correctness ================= */
    uint64_t occTotal=0, occKeptRead=0, aBadMid=0, aBadFwdBase=0, aOob=0;
    /* o = per-occurrence canonical orientation (0 fwd == key, 1 == RC(key)). */
    struct Member{ std::string name; uint32_t snpCol; uint32_t L; int o; };
    std::unordered_map<uint64_t,std::vector<Member>> byKey;      /* allele bucket */
    std::unordered_map<uint64_t,std::vector<uint64_t>> keysBySplit;

    /* Valid stored SNP columns of a (key, readName, strand) triple. The producer
     * places each occurrence in the canonical k-mer strand o and stores the SNP
     * column in that strand's frame (o==0 -> snpCol, o==1 -> L - snpCol); the RC
     * anchor mirrors it to the opposite strand at L - storedCol. A key may occur
     * several times on one read (a repeat); such reads are DROPPED, so a valid
     * (key,read,strand) has exactly one column. Layer C checks storedPos against
     * this set. Key string: name + "\t" + hex(key) + "\t" + strand. */
    std::unordered_map<std::string,std::vector<uint32_t>> validCols;
    /* readName -> read length (kept reads only). */
    std::unordered_map<std::string,uint32_t> readLenOf;

    for(size_t r=0;r<idx.n_reads;++r){
        const MyloReadMarkers& R=idx.reads[r];
        std::string nm(R.name,R.name_len);
        auto kit=keptLen.find(nm);
        auto sit=seqByName.find(nm);
        if(sit==seqByName.end()){ occTotal+=R.n_snpmers; continue; }
        const std::string& seq=sit->second; const uint32_t L=(uint32_t)seq.size();

        for(size_t s=0;s<R.n_snpmers;++s){
            ++occTotal;
            const uint32_t pos=R.snpmers[s].pos; const uint64_t key=R.snpmers[s].key;
            if((uint64_t)pos+(uint64_t)k>L){++aOob;continue;}
            const uint32_t snpCol=pos+(uint32_t)mid;

            /* A1: canonical middle base must decode 0..3 */
            const uint8_t canonMid=(uint8_t)((key>>(2*mid))&3ULL);
            if(canonMid>3){++aBadMid;continue;}
            /* A2: forward read base at snpCol must be a real base */
            const uint8_t fwdMid=enc(seq[snpCol]);
            if(fwdMid==255){++aBadFwdBase;continue;}
            /* A3 (sanity): the canonical middle base equals the read's base on
             * one of the two strands. On strand0 it's fwdMid; on strand1 it's
             * 3-fwdMid (complement). canonMid must be one of these. */
            if(canonMid!=fwdMid && canonMid!=(uint8_t)(3-fwdMid)){++aBadMid;continue;}

            /* Only dinara-kept reads participate in producer prediction. */
            if(kit==keptLen.end()) continue;
            ++occKeptRead;

            /* Per-occurrence orientation and the SNP column in that frame. */
            const int o = (canonMid==fwdMid) ? 0 : 1;
            const uint32_t canonCol = (o==0) ? snpCol : (L - snpCol);
            if(canonCol<1 || (uint64_t)canonCol+1>=L) continue; /* producer OOB */

            byKey[key].push_back(Member{nm,snpCol,L,o});
            readLenOf[nm]=L;
            const uint64_t split=key&splitMask;
            auto& ks=keysBySplit[split];
            if(std::find(ks.begin(),ks.end(),key)==ks.end()) ks.push_back(key);
        }
    }

    /* ============ LAYER B: replicate producer gates & predict ============ */
    /* DROP any read that occurs more than once in the SAME allele (repeat key:
     * ambiguous column). This matches the producer, which removes such reads
     * entirely rather than keeping an arbitrary copy. */
    uint64_t repeatDropped=0;
    for(auto& kv:byKey){
        auto& m=kv.second;
        std::sort(m.begin(),m.end(),[](const Member&a,const Member&b){
            return a.name<b.name; });
        std::vector<Member> kept; kept.reserve(m.size());
        for(size_t i=0;i<m.size();){ size_t j=i;
            while(j<m.size() && m[j].name==m[i].name) ++j;
            if(j-i==1) kept.push_back(m[i]); else repeatDropped+=(j-i);
            i=j; }
        m.swap(kept);
    }
    /* paralog drop: read shared by >1 allele of a split */
    for(auto& sk:keysBySplit){
        auto& keys=sk.second; if(keys.size()<2) continue;
        std::unordered_map<std::string,uint32_t> readCount;
        for(uint64_t key:keys) for(auto& m:byKey[key]) readCount[m.name]++;
        for(uint64_t key:keys){
            auto& m=byKey[key];
            m.erase(std::remove_if(m.begin(),m.end(),[&](const Member&x){
                return readCount[x.name]>1; }),m.end());
        }
    }

    /* Predicted placement SET: (key, name, strand). For each surviving member,
     * the canonical anchor sits on strand o at column canonCol, and the RC
     * anchor on strand o^1 at column L-canonCol. Record the valid stored column
     * for each (key,name,strand) so Layer C can check the exact position. */
    struct PKey{ uint64_t key; std::string name; int strand;
        bool operator==(const PKey&o)const{
            return key==o.key&&strand==o.strand&&name==o.name; } };
    struct PKeyHash{ size_t operator()(const PKey&p)const{
        return std::hash<uint64_t>()(p.key)^(std::hash<std::string>()(p.name)*1315423911u)
               ^(size_t)(p.strand*2654435761u); } };
    std::unordered_set<PKey,PKeyHash> predicted;
    auto recordCol=[&](uint64_t key,const std::string& name,int strand,uint32_t col){
        char kb[24]; snprintf(kb,sizeof(kb),"%016llx",(unsigned long long)key);
        validCols[name+"\t"+kb+"\t"+std::to_string(strand)].push_back(col);
    };

    uint64_t sitesEmitted=0, allelesAppended=0;
    for(auto& sk:keysBySplit){
        auto& keys=sk.second;
        uint64_t surviving=0;
        for(uint64_t key:keys) if(byKey[key].size()>=minMembers) ++surviving;
        if(surviving<2) continue;                 /* requireBiallelic */
        bool emitted=false;
        for(uint64_t key:keys){
            auto& m=byKey[key];
            if(m.size()<minMembers) continue;
            for(auto& x:m){
                const uint32_t canonCol=(x.o==0)? x.snpCol : (x.L - x.snpCol);
                const uint32_t rcCol   = x.L - canonCol;
                predicted.insert(PKey{key,x.name,x.o});
                predicted.insert(PKey{key,x.name,x.o^1});
                recordCol(key,x.name,x.o,   canonCol);
                recordCol(key,x.name,x.o^1, rcCol);
            }
            ++allelesAppended; emitted=true;
        }
        if(emitted) ++sitesEmitted;
    }
    (void)repeatDropped;

    /* ================ LAYER C: cross-check vs dinara dump ================ */
    std::unordered_map<PKey,uint32_t,PKeyHash> dumped;
    {
        FILE* f=fopen(dump,"r"); if(!f){fprintf(stderr,"open %s failed\n",dump);return 2;}
        char* line=nullptr; size_t cap=0; ssize_t n;
        while((n=getline(&line,&cap,f))>0){
            if(line[0]=='#') continue;
            /* key \t anchorId \t side \t readName \t strand \t storedPos */
            char* p=line;
            char* t1=strchr(p,'\t'); if(!t1)continue;
            char* t2=strchr(t1+1,'\t'); if(!t2)continue;
            char* t3=strchr(t2+1,'\t'); if(!t3)continue;
            char* t4=strchr(t3+1,'\t'); if(!t4)continue;
            char* t5=strchr(t4+1,'\t'); if(!t5)continue;
            uint64_t key=strtoull(p,nullptr,16);
            std::string name(t3+1,t4-(t3+1));
            int strand=(int)strtol(t4+1,nullptr,10);
            uint32_t storedPos=(uint32_t)strtoul(t5+1,nullptr,10);
            dumped[PKey{key,name,strand}]=storedPos;
        }
        free(line); fclose(f);
    }

    /* Helper: is `col` a valid stored column of (key,name,strand)? */
    auto isValidCol=[&](uint64_t key,const std::string& name,int strand,uint32_t col)->bool{
        char kb[24]; snprintf(kb,sizeof(kb),"%016llx",(unsigned long long)key);
        auto it=validCols.find(name+"\t"+kb+"\t"+std::to_string(strand));
        if(it==validCols.end()) return false;
        return std::find(it->second.begin(),it->second.end(),col)!=it->second.end();
    };

    /* C1: every predicted (key,read,strand) must appear in the dump.
     * C2: every dumped row must have been predicted.
     * C3: every dumped storedPos must equal the predicted stored column for
     *     that (key,read,strand). */
    uint64_t matched=0, badPos=0, missingInDump=0, extraInDump=0;
    for(auto& pk:predicted){
        if(dumped.find(pk)==dumped.end()){ ++missingInDump;
            if(missingInDump<=5)
                fprintf(stderr,"[MISS] key=%016llx %s str%d not in dump\n",
                    (unsigned long long)pk.key,pk.name.c_str(),pk.strand);
        }
    }
    for(auto& kv:dumped){
        const PKey& pk=kv.first; const uint32_t storedPos=kv.second;
        if(predicted.find(pk)==predicted.end()){ ++extraInDump;
            if(extraInDump<=5)
                fprintf(stderr,"[XTRA] key=%016llx %s str%d pos=%u not predicted\n",
                    (unsigned long long)pk.key,pk.name.c_str(),pk.strand,storedPos);
            continue;
        }
        if(!isValidCol(pk.key,pk.name,pk.strand,storedPos)){ ++badPos;
            if(badPos<=5)
                fprintf(stderr,"[POS ] key=%016llx %s str%d storedPos=%u not a predicted column\n",
                    (unsigned long long)pk.key,pk.name.c_str(),pk.strand,storedPos);
            continue;
        }
        ++matched;
    }

    /* ============================ report ============================ */
    printf("=== SNPmer -> dinara anchor validation ===\n");
    printf("-- Layer A (SNP-column correctness, all reads) --\n");
    printf("  occurrences total            : %llu\n",(unsigned long long)occTotal);
    printf("  bad canonical middle base    : %llu\n",(unsigned long long)aBadMid);
    printf("  forward base not ACGT        : %llu\n",(unsigned long long)aBadFwdBase);
    printf("  k-mer window OOB             : %llu\n",(unsigned long long)aOob);
    printf("  occurrences on kept reads    : %llu\n",(unsigned long long)occKeptRead);
    printf("-- Layer B (producer prediction) --\n");
    printf("  sites emitted                : %llu\n",(unsigned long long)sitesEmitted);
    printf("  allele anchors predicted     : %llu\n",(unsigned long long)allelesAppended);
    printf("  predicted placements         : %zu\n",predicted.size());
    printf("-- Layer C (cross-check vs dinara store) --\n");
    printf("  dumped placements            : %zu\n",dumped.size());
    printf("  predicted placements (set)   : %zu\n",predicted.size());
    printf("  matched (in set + valid col) : %llu\n",(unsigned long long)matched);
    printf("  storedPos not a SNP column   : %llu\n",(unsigned long long)badPos);
    printf("  predicted missing from dump  : %llu\n",(unsigned long long)missingInDump);
    printf("  extra in dump (unpredicted)  : %llu\n",(unsigned long long)extraInDump);

    const bool ok = (aBadMid==0 && aBadFwdBase==0) &&
                    badPos==0 && missingInDump==0 && extraInDump==0 &&
                    matched==dumped.size() && predicted.size()==dumped.size();
    printf("\nRESULT: %s\n", ok? "PASS" : "FAIL");
    return ok?0:1;
}
