/*
 * Independent end-to-end validation that every SNPmer generated by myloasm
 * becomes a dinara anchor at the correct position.
 *
 * Three layers of checking:
 *
 *  A. SNP-column correctness (per occurrence, independent of dinara):
 *     for each snpmer marker on a read, the canonical middle base of the key
 *     must equal one of the two alleles of the k-mer, and the FORWARD read base
 *     at snpCol = pos + mid must decode to a base -- i.e. snpCol is a real SNP
 *     column inside the read.
 *
 *  B. Producer-model prediction (replicates Shasta2SnpmerAnchors.cpp EXACTLY):
 *     bucket occurrences on dinara-KEPT reads by canonical key, dedup a read
 *     seen twice in one allele, drop reads shared by both alleles of a split,
 *     require both alleles >= minMembers (biallelic). For every surviving
 *     member predict the two stored anchor positions:
 *         canon (strand 0): snpCol
 *         rc    (strand 1): L - snpCol
 *     (appendHetAnchorPair stores rawPosition + hetK/2 = snpCol, and mirrors to
 *      L - rawPosition - hetK + hetK/2 = L - snpCol.)
 *
 *  C. Cross-check vs dinara's actual store (DINARA_SNPMER_DUMP output):
 *     the predicted (key, readName, strand, storedPos) set must EQUAL the dumped
 *     set -- no missing predictions, no extra dump rows, and every position must
 *     match exactly.
 *
 * Usage:
 *   validate_snpmer_anchors <reads.fastq> <ReadSummary.csv> <dump.tsv> [threads]
 */
#include "myloasm_ffi.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <zlib.h>

static inline uint8_t enc(char c){
    switch(c){case 'A':case 'a':return 0;case 'C':case 'c':return 1;
              case 'G':case 'g':return 2;case 'T':case 't':return 3;default:return 255;}
}

static void readFastq(const char* file,
                      std::unordered_map<std::string,std::string>& out){
    gzFile fp=gzopen(file,"r"); if(!fp){fprintf(stderr,"gzopen %s failed\n",file);exit(1);}
    char buf[1<<16]; int field=0; std::string name;
    auto gl=[&](std::string& d)->bool{d.clear();
        while(gzgets(fp,buf,sizeof(buf))){d+=buf;
            if(!d.empty()&&d.back()=='\n'){d.pop_back();return true;}}
        return !d.empty();};
    std::string l;
    while(gl(l)){
        if(field==0){size_t sp=l.find_first_of(" \t");
            name=l.substr(1,(sp==std::string::npos?l.size():sp)-1);}
        else if(field==1){out[name]=l;}
        field=(field+1)&3;
    }
    gzclose(fp);
}

/* dinara ReadSummary.csv -> set of kept read names (+ their length). */
static void readSummary(const char* file,
                        std::unordered_map<std::string,uint32_t>& keptLen){
    FILE* f=fopen(file,"r"); if(!f){fprintf(stderr,"open %s failed\n",file);exit(1);}
    char* line=nullptr; size_t cap=0; ssize_t n; bool header=true;
    while((n=getline(&line,&cap,f))>0){
        if(header){header=false;continue;}
        /* Id,Name,Length,... */
        char* p=line; char* c1=strchr(p,','); if(!c1)continue;
        char* c2=strchr(c1+1,','); if(!c2)continue;
        char* c3=strchr(c2+1,','); if(!c3)continue;
        std::string name(c1+1,c2-(c1+1));
        uint32_t len=(uint32_t)strtoul(c2+1,nullptr,10);
        keptLen[name]=len;
    }
    free(line); fclose(f);
}

int main(int argc,char** argv){
    if(argc<4){
        fprintf(stderr,"usage: %s <reads.fastq> <ReadSummary.csv> <dump.tsv> [threads]\n",argv[0]);
        return 2;
    }
    const char* fastq=argv[1]; const char* summary=argv[2]; const char* dump=argv[3];
    int threads=argc>=5?atoi(argv[4]):8;

    /* ---- index reads with myloasm (same call dinara makes) ---- */
    const char* files[1]={fastq};
    MyloReadIndex idx; std::memset(&idx,0,sizeof(idx));
    if(myloasm_index_reads(files,1,0,0,threads,&idx)!=0){
        fprintf(stderr,"myloasm_index_reads failed\n"); return 2;
    }
    const int k=idx.k, mid=(k-1)/2;
    fprintf(stderr,"[val] myloasm reads=%zu k=%d\n",idx.n_reads,k);

    std::unordered_map<std::string,std::string> seqByName; readFastq(fastq,seqByName);
    std::unordered_map<std::string,uint32_t> keptLen; readSummary(summary,keptLen);
    fprintf(stderr,"[val] fastq parsed=%zu, dinara-kept reads=%zu\n",
            seqByName.size(),keptLen.size());

    const uint64_t fullMask=(k>=32)?~0ULL:((1ULL<<(2*k))-1ULL);
    const uint64_t splitMask=fullMask & ~(3ULL<<(2*mid));
    const uint64_t minMembers=2;

    /* ================= LAYER A: SNP-column correctness ================= */
    uint64_t occTotal=0, occKeptRead=0, aBadMid=0, aBadFwdBase=0, aOob=0;
    struct Member{ std::string name; uint32_t snpCol; uint32_t L; };
    std::unordered_map<uint64_t,std::vector<Member>> byKey;      /* allele bucket */
    std::unordered_map<uint64_t,std::vector<uint64_t>> keysBySplit;

    /* All valid SNP columns of a (key, readName) pair. A key can occur at
     * several positions on one read (a repeat); the producer's dedup keeps ONE
     * of them, but WHICH one is an order-dependent tiebreak. Correctness only
     * requires the stored anchor position to be a genuine SNP column of that key
     * on that read, so Layer C checks storedPos against this set, not a single
     * predicted occurrence. Key: name + "\t" + hex(key). */
    std::unordered_map<std::string,std::vector<uint32_t>> validCols;
    /* readName -> read length (kept reads only). */
    std::unordered_map<std::string,uint32_t> readLenOf;

    for(size_t r=0;r<idx.n_reads;++r){
        const MyloReadMarkers& R=idx.reads[r];
        std::string nm(R.name,R.name_len);
        auto kit=keptLen.find(nm);
        auto sit=seqByName.find(nm);
        if(sit==seqByName.end()){ occTotal+=R.n_snpmers; continue; }
        const std::string& seq=sit->second; const uint32_t L=(uint32_t)seq.size();

        for(size_t s=0;s<R.n_snpmers;++s){
            ++occTotal;
            const uint32_t pos=R.snpmers[s].pos; const uint64_t key=R.snpmers[s].key;
            if((uint64_t)pos+(uint64_t)k>L){++aOob;continue;}
            const uint32_t snpCol=pos+(uint32_t)mid;

            /* A1: canonical middle base must decode 0..3 */
            const uint8_t canonMid=(uint8_t)((key>>(2*mid))&3ULL);
            if(canonMid>3){++aBadMid;continue;}
            /* A2: forward read base at snpCol must be a real base */
            const uint8_t fwdMid=enc(seq[snpCol]);
            if(fwdMid==255){++aBadFwdBase;continue;}
            /* A3 (sanity): the canonical middle base equals the read's base on
             * one of the two strands. On strand0 it's fwdMid; on strand1 it's
             * 3-fwdMid (complement). canonMid must be one of these. */
            if(canonMid!=fwdMid && canonMid!=(uint8_t)(3-fwdMid)){++aBadMid;continue;}

            /* Only dinara-kept reads participate in producer prediction. */
            if(kit==keptLen.end()) continue;
            ++occKeptRead;
            if(snpCol<1 || (uint64_t)snpCol+1>=L) continue; /* producer OOB gate */

            byKey[key].push_back(Member{nm,snpCol,L});
            readLenOf[nm]=L;
            {   /* record this as a valid SNP column for (key,read) */
                char kb[24]; snprintf(kb,sizeof(kb),"%016llx",(unsigned long long)key);
                validCols[nm+"\t"+kb].push_back(snpCol);
            }
            const uint64_t split=key&splitMask;
            auto& ks=keysBySplit[split];
            if(std::find(ks.begin(),ks.end(),key)==ks.end()) ks.push_back(key);
        }
    }

    /* ============ LAYER B: replicate producer gates & predict ============ */
    /* dedup a read seen twice in the SAME allele (keep first) */
    for(auto& kv:byKey){
        auto& m=kv.second;
        std::sort(m.begin(),m.end(),[](const Member&a,const Member&b){
            return a.name<b.name; });
        m.erase(std::unique(m.begin(),m.end(),[](const Member&a,const Member&b){
            return a.name==b.name; }),m.end());
    }
    /* paralog drop: read shared by >1 allele of a split */
    for(auto& sk:keysBySplit){
        auto& keys=sk.second; if(keys.size()<2) continue;
        std::unordered_map<std::string,uint32_t> readCount;
        for(uint64_t key:keys) for(auto& m:byKey[key]) readCount[m.name]++;
        for(uint64_t key:keys){
            auto& m=byKey[key];
            m.erase(std::remove_if(m.begin(),m.end(),[&](const Member&x){
                return readCount[x.name]>1; }),m.end());
        }
    }

    /* Predicted placement SET: which (key, name, strand) pairs must appear in
     * the store. This set is order-independent (dedup only removes duplicate
     * READS, and a read either survives all gates or not). The exact stored
     * POSITION is validated separately in Layer C against validCols, because
     * for a repeat key the surviving occurrence's column is a tiebreak choice. */
    struct PKey{ uint64_t key; std::string name; int strand;
        bool operator==(const PKey&o)const{
            return key==o.key&&strand==o.strand&&name==o.name; } };
    struct PKeyHash{ size_t operator()(const PKey&p)const{
        return std::hash<uint64_t>()(p.key)^(std::hash<std::string>()(p.name)*1315423911u)
               ^(size_t)(p.strand*2654435761u); } };
    std::unordered_set<PKey,PKeyHash> predicted;

    uint64_t sitesEmitted=0, allelesAppended=0;
    for(auto& sk:keysBySplit){
        auto& keys=sk.second;
        uint64_t surviving=0;
        for(uint64_t key:keys) if(byKey[key].size()>=minMembers) ++surviving;
        if(surviving<2) continue;                 /* requireBiallelic */
        bool emitted=false;
        for(uint64_t key:keys){
            auto& m=byKey[key];
            if(m.size()<minMembers) continue;
            for(auto& x:m){
                predicted.insert(PKey{key,x.name,0});   /* canon strand0 */
                predicted.insert(PKey{key,x.name,1});   /* rc    strand1 */
            }
            ++allelesAppended; emitted=true;
        }
        if(emitted) ++sitesEmitted;
    }

    /* ================ LAYER C: cross-check vs dinara dump ================ */
    std::unordered_map<PKey,uint32_t,PKeyHash> dumped;
    {
        FILE* f=fopen(dump,"r"); if(!f){fprintf(stderr,"open %s failed\n",dump);return 2;}
        char* line=nullptr; size_t cap=0; ssize_t n;
        while((n=getline(&line,&cap,f))>0){
            if(line[0]=='#') continue;
            /* key \t anchorId \t side \t readName \t strand \t storedPos */
            char* p=line;
            char* t1=strchr(p,'\t'); if(!t1)continue;
            char* t2=strchr(t1+1,'\t'); if(!t2)continue;
            char* t3=strchr(t2+1,'\t'); if(!t3)continue;
            char* t4=strchr(t3+1,'\t'); if(!t4)continue;
            char* t5=strchr(t4+1,'\t'); if(!t5)continue;
            uint64_t key=strtoull(p,nullptr,16);
            std::string name(t3+1,t4-(t3+1));
            int strand=(int)strtol(t4+1,nullptr,10);
            uint32_t storedPos=(uint32_t)strtoul(t5+1,nullptr,10);
            dumped[PKey{key,name,strand}]=storedPos;
        }
        free(line); fclose(f);
    }

    /* Helper: is `col` a valid SNP column of (key,name)? */
    auto isValidCol=[&](uint64_t key,const std::string& name,uint32_t col)->bool{
        char kb[24]; snprintf(kb,sizeof(kb),"%016llx",(unsigned long long)key);
        auto it=validCols.find(name+"\t"+kb);
        if(it==validCols.end()) return false;
        return std::find(it->second.begin(),it->second.end(),col)!=it->second.end();
    };

    /* C1: every predicted (key,read,strand) must appear in the dump.
     * C2: every dumped row must have been predicted.
     * C3: every dumped storedPos must be a genuine SNP column:
     *       strand0: storedPos itself
     *       strand1: L - storedPos   (canon column mirrored back) */
    uint64_t matched=0, badPos=0, missingInDump=0, extraInDump=0;
    for(auto& pk:predicted){
        if(dumped.find(pk)==dumped.end()){ ++missingInDump;
            if(missingInDump<=5)
                fprintf(stderr,"[MISS] key=%016llx %s str%d not in dump\n",
                    (unsigned long long)pk.key,pk.name.c_str(),pk.strand);
        }
    }
    for(auto& kv:dumped){
        const PKey& pk=kv.first; const uint32_t storedPos=kv.second;
        if(predicted.find(pk)==predicted.end()){ ++extraInDump;
            if(extraInDump<=5)
                fprintf(stderr,"[XTRA] key=%016llx %s str%d pos=%u not predicted\n",
                    (unsigned long long)pk.key,pk.name.c_str(),pk.strand,storedPos);
            continue;
        }
        uint32_t canonCol;
        if(pk.strand==0) canonCol=storedPos;
        else { auto lit=readLenOf.find(pk.name);
               if(lit==readLenOf.end()){ ++badPos; continue; }
               canonCol=lit->second - storedPos; }
        if(!isValidCol(pk.key,pk.name,canonCol)){ ++badPos;
            if(badPos<=5)
                fprintf(stderr,"[POS ] key=%016llx %s str%d storedPos=%u canonCol=%u not a valid SNP column\n",
                    (unsigned long long)pk.key,pk.name.c_str(),pk.strand,storedPos,canonCol);
            continue;
        }
        ++matched;
    }

    /* ============================ report ============================ */
    printf("=== SNPmer -> dinara anchor validation ===\n");
    printf("-- Layer A (SNP-column correctness, all reads) --\n");
    printf("  occurrences total            : %llu\n",(unsigned long long)occTotal);
    printf("  bad canonical middle base    : %llu\n",(unsigned long long)aBadMid);
    printf("  forward base not ACGT        : %llu\n",(unsigned long long)aBadFwdBase);
    printf("  k-mer window OOB             : %llu\n",(unsigned long long)aOob);
    printf("  occurrences on kept reads    : %llu\n",(unsigned long long)occKeptRead);
    printf("-- Layer B (producer prediction) --\n");
    printf("  sites emitted                : %llu\n",(unsigned long long)sitesEmitted);
    printf("  allele anchors predicted     : %llu\n",(unsigned long long)allelesAppended);
    printf("  predicted placements         : %zu\n",predicted.size());
    printf("-- Layer C (cross-check vs dinara store) --\n");
    printf("  dumped placements            : %zu\n",dumped.size());
    printf("  predicted placements (set)   : %zu\n",predicted.size());
    printf("  matched (in set + valid col) : %llu\n",(unsigned long long)matched);
    printf("  storedPos not a SNP column   : %llu\n",(unsigned long long)badPos);
    printf("  predicted missing from dump  : %llu\n",(unsigned long long)missingInDump);
    printf("  extra in dump (unpredicted)  : %llu\n",(unsigned long long)extraInDump);

    const bool ok = (aBadMid==0 && aBadFwdBase==0) &&
                    badPos==0 && missingInDump==0 && extraInDump==0 &&
                    matched==dumped.size() && predicted.size()==dumped.size();
    printf("\nRESULT: %s\n", ok? "PASS" : "FAIL");
    return ok?0:1;
}
